jupyterhub/nativeauthenticator

nativeauthenticator/handlers.py, nativeauthenticator/nativeauthenticator.py, nativeauthenticator/templates/signup.html
=> Add new user

nativeauthenticator/nativeauthenticator.py, nativeauthenticator/orm.py
Added a relationship between default `User` model from JupyterHub and `UserInfo` model from this Authenticator. Thanks for your help @dedeco!
Closes #26
=> Add relationship between User and UserInfo

nativeauthenticator/templates/autorization-area.html
=> Add missing template from authorization page

nativeauthenticator/templates/signup.html
=> Add option to see password on signup

docs/options.rst, nativeauthenticator/handlers.py, nativeauthenticator/nativeauthenticator.py, nativeauthenticator/templates/signup.html, nativeauthenticator/tests/test_authenticator.py
=> Add option for open signup and add style to result msgs

docs/index.rst, nativeauthenticator/handlers.py, nativeauthenticator/nativeauthenticator.py, nativeauthenticator/templates/change-password.html, nativeauthenticator/tests/test_authenticator.py
=> Add endpoint for changing password

nativeauthenticator/handlers.py
Move message handling to a separate function other then the post method on the SignUp Handler
=> Remove message decision from Signup post method

.gitignore, nativeauthenticator/handlers.py, setup.py
=> Fix installation errors

nativeauthenticator/nativeauthenticator.py, nativeauthenticator/tests/test_authenticator.py
=> Delete user info from admin panel

setup.py
The solution to the problem mentioned on #51 and #52 was found [on this link](https://setuptools.readthedocs.io/en/latest/setuptools.html#including-data-files) about including data files on packaging
=> Fix data packaging on setup.py

setup.py
And updating to version 0.0.3.
Tested it locally following [this response](https://stackoverflow.com/a/41093798/3538098) and it works now.
=> Change package_data to include_package_data

nativeauthenticator/handlers.py
=> Fix failed to change password due to compatibility issues with JupyterHub 1.0.0

nativeauthenticator/nativeauthenticator.py
=> Add normalization to username

.gitignore, README.md, nativeauthenticator/nativeauthenticator.py, nativeauthenticator/templates/change-password.html, nativeauthenticator/templates/native-login.html, nativeauthenticator/templates/signup.html
* `pip install` in README.md was missing the `-r` flag
* use set of common passwords to perform search with constant time instead of linear
* use `os.path.exists(dir + file)` instead of `file in os.listdir(dir)`
* fix various html and js typos: `===` instead of `==`, empty tags, missing labels for inputs, unclosed tags
=> fix typos and improve performance

nativeauthenticator/nativeauthenticator.py
Reverts jupyterhub/nativeauthenticator#82
=> Revert "fix timedelta.seconds misuse"

nativeauthenticator/handlers.py, nativeauthenticator/nativeauthenticator.py, nativeauthenticator/templates/change-password.html
Add endpoint to allow admin to change the password for any users.
https://github.com/jupyterhub/nativeauthenticator/issues/90
=> Allow admin to change any password

nativeauthenticator/nativeauthenticator.py
=> Allowed users

CHANGELOG.md
The changelog only had an entry for the 0.0.5 release. As I wanted to review changes over time to debug an issue I was pinged in I figured I'll add this retrospectively.
=> Update changelog from 0.0.1-0.0.7

README.md
I positioned the badges a bit off the top to avoid a merge conflict with #134 to be fixed later.
=> Add various README badges

nativeauthenticator/handlers.py, nativeauthenticator/templates/autorization-area.html
Just add an anchor to avoid scrolling at each change of authorization .
Closes #131.
Regards
=> feat: keep position in authorization area

docs/options.rst, nativeauthenticator/handlers.py, nativeauthenticator/nativeauthenticator.py, nativeauthenticator/templates/signup.html
Option to include a checkbox to force acceptance of Terms of Service before SignUp if desired.
=> Terms of Service

nativeauthenticator/templates/native-login.html, nativeauthenticator/templates/signup.html
=> Use XSRF tokens for cross-site protections

.github/workflows/test.yaml
=> pin sqlalchemy 1 on jupyterhub 1 and 2

.pre-commit-config.yaml, dev-jupyterhub_config.py, nativeauthenticator/crypto/crypto.py, nativeauthenticator/crypto/signing.py, nativeauthenticator/handlers.py, nativeauthenticator/nativeauthenticator.py, nativeauthenticator/orm.py, nativeauthenticator/tests/test_authenticator.py, pyproject.toml, setup.py
This aligns the project what we do across the jupyterhub org overall.
=> pre-commit: add autoflake, use isort over reorder-python-imports

.github/workflows/test.yaml, CONTRIBUTING.md, MANIFEST.in, README.md, dev-requirements.txt, nativeauthenticator/tests/conftest.py, nativeauthenticator/tests/test_authenticator.py, nativeauthenticator/tests/test_orm.py, pyproject.toml, setup.py
Besides adding test an an optional dependency, and fixing and migrating codecov to non-deprecated way of reporting code coverage, this is just refactoring for readability and to align with various setups in the jupyterhub org.
=> Add test as optional dependency, refactor fixtures to conftest.py, fix code coverage setup
