jupyterhub/nativeauthenticator

- .travis.yml
- README.md
- dev-requirements.txt
- nativeauthenticator/nativeauthenticator.py
- setup.py
- tests/test_authenticator.py
Added a minimum infra-structure for tests using as a base [this pull-request](https://github.com/jupyterhub/firstuseauthenticator/pull/9/files).
> Add minimal tests

- dev-requirements.txt
- nativeauthenticator/nativeauthenticator.py
- nativeauthenticator/orm.py
- nativeauthenticator/tests/test_authenticator.py
> Add authentication based on userinfo

- nativeauthenticator/handlers.py
- nativeauthenticator/nativeauthenticator.py
- nativeauthenticator/orm.py
- nativeauthenticator/tests/test_authenticator.py
This pull request closes all tasks on #19 and #20 
The Authorization area looks like this:
> Add admin authorization system to new users

- docs/index.rst
- docs/options.rst
- docs/quickstart.rst
Adding documentation for features I did previously
> Improve docs

- docs/index.rst
- docs/options.rst
- nativeauthenticator/nativeauthenticator.py
- nativeauthenticator/tests/test_authenticator.py
> Add check if user exceeded attempt of logins

- docs/index.rst
- nativeauthenticator/handlers.py
- nativeauthenticator/nativeauthenticator.py
- nativeauthenticator/tests/test_authenticator.py
Closes #39 
Since we did this on FirstUse Authenticator, I assumed this would be important here too
> Username sanitization

- nativeauthenticator/handlers.py
- nativeauthenticator/nativeauthenticator.py
- nativeauthenticator/templates/signup.html
When creating a new user with email, the handler was not passing this information to the function `get_or_create_user` and the email was not being stored. This fixes this problem
> Add all info from signup post to get_or_create_user

- MANIFEST.in
without this, files including package-data doesn’t get included
in releases
> add MANIFEST.in to ensure files get packaged

- nativeauthenticator/orm.py
Hi @leportella 
When I want to sign up a new user, it just show `Something went wrong. Be sure your password doesn't have spaces or commas and is not too common.`. Then, I just add a traceback and shows like:
```
Traceback (most recent call last):
File "/home/kai/work/embark3_env/nativeauthenticator/nativeauthenticator/nativeauthenticator.py", line 156, in get_or_create_user
user_info = UserInfo(**infos)
File "<string>", line 4, in __init__
File "/home/kai/work/embark3_env/venv/lib/python3.5/site-packages/sqlalchemy/orm/state.py", line 424, in _initialize_instance
manager.dispatch.init_failure(self, args, kwargs)
File "/home/kai/work/embark3_env/venv/lib/python3.5/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
compat.reraise(exc_type, exc_value, exc_tb)
File …
```
> fix raise error when email is none

- nativeauthenticator/nativeauthenticator.py
- nativeauthenticator/tests/test_authenticator.py
Some pull requests ago, I added the creation of a User when UserInfo was created on SignUp.
However, this behavior is returning problems because Users are already created when a user login. So, the duplication was returning an error, specially for admins that have their users created previously.
> Remove duplication creation of user

- nativeauthenticator/orm.py
- nativeauthenticator/tests/test_orm.py
Hi @leportella . I use mysql database as backend.
The log:
```
HTTPServerRequest(protocol='http', host='localhost:8000', method='POST', uri='/hub/login?next=', version='HTTP/1.1', remote_ip='::ffff:127.0.0.1')
Traceback (most recent call last):
File "/home/kai/work/embark3_env/venv/lib/python3.5/site-packages/tornado/web.py", line 1592, in _execute
result = yield result
File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
raise self._exception
File "/home/kai/work/embark3_env/venv/lib/python3.5/site-packages/jupyterhub/handlers/login.py", line 82, in post
user = yield self.login_user(data)
File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
raise self._exception
File "/home/kai/work/embark3_env/venv/lib/python3.5/site-packages/jupyterhub/handlers/base.py", line …
```
> fix password is not bytes in mysql

- nativeauthenticator/orm.py
`otp_secret` should be `varying(16)` since `base64.b32encode(os.urandom(10)).decode('utf-8')` produces a string of length 16. sqlite3 didn't yell about this but postgres did.
> postgres says `opt_secret` is too long for `varying(10)`

- nativeauthenticator/templates/native-login.html
This PR handles the `announcement_login` template var in the same way as the [default login template](https://github.com/jupyterhub/jupyterhub/blob/master/share/jupyterhub/templates/login.html#L2-L4)
> Add announcement_login handling to login template

- nativeauthenticator/nativeauthenticator.py
Currently, the authenticator complains during signup if you enter a password that has exactly the minimum length and suggest you enter a password of at least the minimum length.
This could lead to confusion for the users. This pull request makes the authenticator also accept passwords that are the exact minimum length.
> Authenticator should accept passwords that are exactly the minimum length

- nativeauthenticator/nativeauthenticator.py
`timedelta.seconds` is the number of seconds in the remaining day and is always < 86399. What you meant is `timedelta.total_seconds()`
See: https://stackoverflow.com/questions/51652952/python-timedelta-seconds-vs-total-seconds
> fix timedelta.seconds misuse

- nativeauthenticator/nativeauthenticator.py
Users who were created via the Admin UI (/hub/admin -> Add Users) but never logged in are not in the db and trying to delete them in the Admin UI throws an exception.
> Add check for None before trying to delete a user.

- docs/options.rst
- nativeauthenticator/handlers.py
- nativeauthenticator/nativeauthenticator.py
- nativeauthenticator/templates/native-login.html
- nativeauthenticator/tests/test_authenticator.py
I find that NativeAuthenticator can only turn off automatic authorization but cannot prevent users registering, so I submit this pr.
> Add option for disable user to signup

- nativeauthenticator/handlers.py
- nativeauthenticator/nativeauthenticator.py
- nativeauthenticator/tests/test_authenticator.py
Fixes #91, including an additional test for signing up with the same username multiple times and a fitting error message on rejected signup.
In the course of this, I refactored the `get_or_create_user()` method into three methods: `user_exists()`, `get_user()` and `create_user()` which gets rid of the signup error (which was related to getting a user when, really, you wanted to create a user).
I also replaced calls to UserInfo without username normalization in the authenticator with calls to the aforementioned `get_user()`, which does include username normalization.
> Error on signup with taken username

- nativeauthenticator/handlers.py
- nativeauthenticator/templates/native-login.html
- nativeauthenticator/templates/signup.html
This is basically a follow-up PR to #102, which introduced a bug that now leads to 500 errors (instead of sensible error messages) when signing up with a taken username. This PR removes this bug.
There are also a few minor improvements that I found along the way. These can be factored out if necessary.
- If the chosen username is taken, the software now also errors, even if during open signup.
- Corrected typos and grammar in a few places.
> Signup error

- nativeauthenticator/handlers.py
The `env.loader` was replaced by a new `ChoiceLoader` wrapping the previous
loader on every render. It seems that the `_loaded` attribute was here
to avoid re-registering the loader but it was set to `True` on the
handler instance and not on its class making it useless since the a
handler instance is created for each request.
Closes #114.
> Ensure that jinja loader is not registered at each render

- nativeauthenticator/handlers.py
Without 'await' tornado raise a type Error (TypeError: write() only accepts bytes, unicode, and dict objects)
Regards
> fix: we now need to await render_template method

- .github/workflows/test.yaml
- CONTRIBUTING.md
- dev-requirements.txt
Now with a .pre-commit-config.yaml and changes made so that the pre-commit checks pass in #173 and #174, we can adopt the service https://pre-commit.ci to help us run these tests with very high speed together with automation to apply auto formatting for those that hasn't installed and let pre-commit run before creating a PR.
The use of pre-commit.ci has been considered in https://github.com/jupyterhub/team-compass/issues/379. I've found the service to be really helpful so far, and there seems to be some tentative agreement towards that.
> ci: rely on pre-commit.ci & run tests only if needed

- nativeauthenticator/nativeauthenticator.py
This project has already transitioned away from gen.coroutine as we could after requiring Python 3.6, but I found one function that had the outdated syntax still.
Note that Python 3.6 is required by JupyterHub 1.3.0, and we require JupyterHub 1.3.0+: https://github.com/jupyterhub/jupyterhub/blob/1.3.0/setup.py#L19-L23
> chore: use async instead of gen.coroutine

- nativeauthenticator/handlers.py
- nativeauthenticator/nativeauthenticator.py
- nativeauthenticator/tests/test_authenticator.py
I did a thorough pass on the handlers and did some documenting and refactoring in a few places (for example, we now no longer have "AuthorizeHandler", "AuthorizationHandler", and "ChangeAuthorizationHandler" that all do vastly different things).
Also simplified the logic on error reporting in a few places.
Ideally, I would hope that this closes #177.
> document and refactor the handlers

- docs/source/quickstart.md
Line 37 of `docs/source/quickstart.md` is incorrect python code. `)` is needed.
before
```python
c.JupyterHub.template_paths = [f"{os.path.dirname(nativeauthenticator.__file__}/templates/"]
```
after
```python
c.JupyterHub.template_paths = [f"{os.path.dirname(nativeauthenticator.__file__)}/templates/"]
```
> docs: fix c.JupyterHub.template_paths

- README.md
- docs/source/options.md
- docs/source/quickstart.md
- docs/source/troubleshooting.md
I understand that it is possible to do `c.Authenticator.something` instead of `c.NativeAuthenticator.something`, but it becomes far less clear for anyone how to search and find help about this if they don't understand if `something` is a NativeAuthenticator feature or a Authenticator base class feature, or simply think it's all part of some base class.
Due to that, I suggest we encourage the use of `c.NativeAuthenticator` by example even though both will work.
---
I've also made a small tweak about using block code examples instead of inline code examples and made us consistently use `shell` as a code language over `bash` but don't know it would matter at all. I've also consistently omitted adding `$ ` which would also be copied if someone used the `copy code` button that are part of the …
> docs: c.NativeAuthenticator instead of c.Authenticator

- nativeauthenticator/handlers.py
- nativeauthenticator/nativeauthenticator.py
Closes #193. Admins that sign up on the system now _don't_ get authorization emails if that feature is enabled. They also now get a "Signup successful, you can log in now" message instead of the (slightly misleading) "Your data has been sent to the admin" now.
And while I was in there, I removed the unnecessary default value for `assume_user_is_human` in `get_result_message` and re-ordered the arguments to place them in the order they are being checked.
> Correct login procedure for admins

- nativeauthenticator/handlers.py
- nativeauthenticator/nativeauthenticator.py
Documentation said that spaces, commas and slasher weren't allowed but only the restriction of commas and spaces was enforced.
> Add slash restriction to username validation

- .github/dependabot.yml
- .github/workflows/publish.yaml
- .github/workflows/test.yaml
I'll go for a quick self-merge on this and creating another PR that may would have a merge conflict with this to test against jupyterhub 3 on python 3.11
> ci: add dependabot bumping of github actions

- .github/workflows/test.yaml
Wieee, tests pass against jupyterhub 3 and python 3.11's release candidate as well!
> ci: add tests against jupyterhub 3 and python 3.11

- RELEASE.md
- tbump.toml
I added a typical RELEASE.md file as most jupyterhub projects has to help anyone make a release in a systematic way. `tbump` is a tool that helps us automate that a bit further as well, also adopted in various jupyterhub repositories.
> ci: add RELEASE.md and tbump.toml

- CHANGELOG.md
Besides adding an entry for 1.1.0, I'm backfilling some notes for 1.0.1-1.0.5 as well, and adjusts the heading level to align with the typical changelogs in other jupyterhub repositories.
I chatted with @lambdaTotoro on twitter who had some vacation time who agreed I could go for a release, so with the approval of @minrk I'll go for one now.
- Closes #214
---
Note that I sprinted and self merged the following just before this:
- #215
- #216
- #217
I'm expediting this to get it as part of the z2jh 2.0.0 release I'd love to make now today (https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/2855)
> Add changelog for 1.1.0

- .github/dependabot.yml
This is one of several PRs opened in the juptyterhub github organization to systematically configure dependabot to update github actions on a monthly basis, for more information see https://github.com/jupyterhub/team-compass/issues/636.
> dependabot: monthly updates of github actions

- dev-jupyterhub_config.py
- docs/source/quickstart.md
- setup.py
This makes it possible to do `c.JupyterHub.authenticator_class = "native"`.
Similar PR in tmpauthenticator:
- https://github.com/jupyterhub/tmpauthenticator/pull/38
> Register native as an jupyterhub authenticator class

- nativeauthenticator/templates/page.html
Fixed page.html template menu bar appearence.
After the fix it appears the correct way:
> Fix page.html menu bar

- .github/workflows/release.yaml
- .github/workflows/test.yaml
- .pre-commit-config.yaml
- pyproject.toml
- setup.py
- fixes #261
Dropping jupyterhub <4 was agreed between me @manics and @minrk, but requiring Python 3.9 hasn't been discussed.
Python 3.8 reaches end of life and won't get security patches in a month, so I figure we could go for a reduction of what versions we support now to exclude 3.8.
> Require jupyterhub 4.1.6+ and Python 3.9+

- nativeauthenticator/handlers.py
- nativeauthenticator/nativeauthenticator.py
Rebased version of #271 where I failed to push a commit with fixes needed as seen by @manics.
- Closes #271
---
Thank you @paolocarinci for spotting this and initializing the work to fix it!!
> Fix user was added on sign-up even if password didn't match confirmation

- .flake8
I expected unitialized variables to be caught by flake8, so I looked at this config to verify we didn't ignore more than usual - but we didn't. Not sure why #275 ended up fixing a previously undetected `user_info` not being initialized.
> Update .flake8 config to match other jupyterhub repos

- CHANGELOG.md
I made this 2.0.0 because of #274, not fully confident if that is what we should do or not.
> Add changelog for 1.3.0
